import dayjs from 'dayjs';

export const timePeriods = [
  {
    section: 'Last',
    values:  [
      {
        key:             'last7d',
        display:         'Last 7 days',
        timeframeText:   'From 7 days ago until now',
        timeframeLength: () => '7d',
        start:           () => dayjs().subtract(7, 'day').toDate(),
        end:             () => dayjs().toDate(),
      },
      {
        key:             'last14d',
        display:         'Last 14 days',
        timeframeText:   'From 14 days ago until now',
        timeframeLength: () => '14d',
        start:           () => dayjs().subtract(14, 'day').toDate(),
        end:             () => dayjs().toDate(),
      },
      {
        key:             'last30d',
        display:         'Last 30 days',
        timeframeText:   'From 30 days ago until now',
        timeframeLength: () => '30d',
        start:           () => dayjs().subtract(30, 'day').toDate(),
        end:             () => dayjs().toDate(),
      },
      {
        key:             'last90d',
        display:         'Last 90 days',
        timeframeText:   'From 90 days ago until now',
        timeframeLength: () => '90d',
        start:           () => dayjs().subtract(90, 'day').toDate(),
        end:             () => dayjs().toDate(),
      },
      {
        key:             'last6m',
        display:         'Last 6 months',
        timeframeText:   'From 6 months ago until now',
        timeframeLength: () => '6mo',
        start:           () => dayjs().subtract(6, 'month').toDate(),
        end:             () => dayjs().toDate(),
      },
      {
        key:             'last12m',
        display:         'Last 12 months',
        timeframeText:   'From 12 months ago until now',
        timeframeLength: () => '12mo',
        start:           () => dayjs().subtract(12, 'month').toDate(),
        end:             () => dayjs().toDate(),
      },
    ],
  },
  {
    section: 'Previous',
    values:  [
      {
        key:             'previous_week',
        display:         'Previous week',
        timeframeText:   'Last week',
        timeframeLength: () => '1w',
        start:           () => dayjs().subtract(1, 'week').startOf('week').toDate(),
        end:             () => dayjs().subtract(1, 'week').endOf('week').toDate(),
      },
      {
        key:             'previous_month',
        display:         'Previous month',
        timeframeText:   'Last month',
        timeframeLength: () => '1mo',
        start:           () => dayjs().subtract(1, 'month').startOf('month').toDate(),
        end:             () => dayjs().subtract(1, 'month').endOf('month').toDate(),
      },
      {
        key:             'previous_year',
        display:         'Previous year',
        timeframeText:   'Last year',
        timeframeLength: () => '1y',
        start:           () => dayjs().subtract(1, 'year').startOf('year').toDate(),
        end:             () => dayjs().subtract(1, 'year').endOf('year').toDate(),
      },
    ],
  },
  {
    section: 'Current',
    values:  [
      {
        key:             'current_week',
        display:         'Current week',
        timeframeText:   'This week',
        timeframeLength: () => '1w',
        start:           () => dayjs().startOf('week').toDate(),
        end:             () => dayjs().endOf('week').toDate(),
      },
      {
        key:             'current_month',
        display:         'Current month',
        timeframeText:   'This month',
        timeframeLength: () => '1mo',
        start:           () => dayjs().startOf('month').toDate(),
        end:             () => dayjs().endOf('month').toDate(),
      },
      {
        key:             'current_year',
        display:         'Current year',
        timeframeText:   'This year',
        timeframeLength: () => '1y',
        start:           () => dayjs().startOf('year').toDate(),
        end:             () => dayjs().endOf('year').toDate(),
      },
    ],
  },
  {
    section: 'Next',
    values:  [
      {
        key:             'next_week',
        display:         'Next week',
        timeframeText:   'Upcoming week',
        timeframeLength: () => '1w',
        start:           () => dayjs().add(1, 'week').startOf('week').toDate(),
        end:             () => dayjs().add(1, 'week').endOf('week').toDate(),
      },
      {
        key:             'next_month',
        display:         'Next month',
        timeframeText:   'Upcoming month',
        timeframeLength: () => '1mo',
        start:           () => dayjs().add(1, 'month').startOf('month').toDate(),
        end:             () => dayjs().add(1, 'month').endOf('month').toDate(),
      },
      {
        key:             'next_3months',
        display:         'Next 3 months',
        timeframeText:   'Upcoming 3 months',
        timeframeLength: () => '3mo',
        start:           () => dayjs().toDate(),
        end:             () => dayjs().add(3, 'month').toDate(),
      },
      {
        key:             'next_6months',
        display:         'Next 6 months',
        timeframeText:   'Upcoming 6 months',
        timeframeLength: () => '6mo',
        start:           () => dayjs().toDate(),
        end:             () => dayjs().add(6, 'month').toDate(),
      },
      {
        key:             'next_year',
        display:         'Next year',
        timeframeText:   'Upcoming year',
        timeframeLength: () => '1y',
        start:           () => dayjs().add(1, 'year').startOf('year').toDate(),
        end:             () => dayjs().add(1, 'year').endOf('year').toDate(),
      },
    ],
  },
];
