FROM node:24-alpine AS build
RUN corepack enable
WORKDIR /repo

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY server/package.json server/package.json
COPY ui/package.json ui/package.json

RUN pnpm install --frozen-lockfile --filter ./ui

COPY . .
RUN pnpm --filter ./ui run build

FROM nginx:1.29-alpine AS nginx
COPY nginx.compose.conf /etc/nginx/nginx.conf
COPY --from=build /repo/ui/dist /app/frontend
EXPOSE 80
