name: CI

on:
  pull_request:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Install deps (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build workspace (server + ui)
        run: pnpm build
