name: CI & Build checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 4"

env:
  ACTIONS_RUNNER_DEBUG: false
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-release-container:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      deployments: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest ${{ github.ref_name }} ${{ github.sha }}
          build-args: |
            JWT_SECRET=${{ secrets.JWT_SECRET }}
          containerfiles: |
            ./Dockerfile
          oci: true

      - name: Print image urls
        run: echo "Images built ${{ toJSON(steps.build-image.outputs) }}"
