name: CI & Build checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 4 * * 4"

permissions:
  contents: read

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        svc:
          - { name: ui,     dockerfile: Dockerfile.ui,     context: . }
          - { name: server, dockerfile: Dockerfile.server, context: . }

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.svc.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.svc.context }}
          file: ${{ matrix.svc.dockerfile }}
          platforms: linux/amd64
          push: false
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/horus-${{ matrix.svc.name }}:test-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show built images
        run: docker images | head -n 20
